# VPC
ec2_vpc_name: VPC_PA
ec2_vpc_region: us-east-1
ec2_vpc_cidr: 10.0.0.0/16
# Subnet
ec2_subnet_name: Subnet_PA
ec2_subnet_cidr: 10.0.0.0/24
ec2_subnet_az: us-east-1a
# Subnet1
ec2_subnet_name1: Subnet_PA_ENI1
ec2_subnet_cidr1: 10.0.1.0/24
# Subnet2
ec2_subnet_name2: Subnet_PA_ENI2
ec2_subnet_cidr2: 10.0.2.0/24
# ENI1
ec2_eni_name1: ENI_PA1
# ENI2
ec2_eni_name2: ENI_PA2
# IGW
ec2_igw_name: IGW_PA
# Route Table
ec2_rt_name: RT_PA
# RHEL Open ports
ec2_sg_name: SG_PA
ec2_sg_openports:
  - 80
  - 443
  - 22

# Paloalto
# AMI
ec2_paloalto_image_id: "ami-0fd5ac27c2061fcc9" # v10.1.14-h6 ami-031c5c1c3673d4428
ec2_paloalto_image_name: "PA-VM-AWS-10.1.14-h6-0825b781-215f-4686-8da2-b95275cc8dd0" # PA-VM-AWS-10.1.14-h6-f1260463-68e1-4bfb-bf2e-075c2664c1d7
# Flavour 
ec2_paloalto_flavor_name: c5n.xlarge
# Key Pair
ec2_paloalto_key_name: "KeyPair-Virginia"
# Instance
ec2_paloalto_instance_name: paloalto-1

# RHEL
# AMI
ec2_rhel_image_name: RHEL-9.5.0_HVM*x86_64*
# Flavour 
ec2_rhel_flavor_name: t2.large
# Disk
ec2_rhel_disk_size: 20
ec2_rhel_ebs_name: /dev/sda1
# Key Pair
ec2_rhel_key_name: "KeyPair-Virginia"
# Instance
ec2_rhel_instance_name: rhel-1

ec2_rhel_user: "{{ ansible_user }}"
ec2_rhel_pass: "{{ ansible_password }}"